// src/registry/componentLibrary.ts

import { ComponentCategory, ComponentDefinition, ComponentLibrary } from '@/lib/dev-container';
import { validateUniqueIds } from './helper';

// Define all available containerized components from shadcn and geenius folders
const componentDefinitions = [
  // =====================================
  // SHADCN COMPONENTS
  // =====================================
  {
    id: 'dev-accordion',
    name: 'Dev Accordion',
    description: 'Development-aware accordion component',
    componentPath: 'src/lib/dev-container/shadcn/Accordion.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Accordion.tsx',
    category: 'ui',
    semanticTags: ['accordion', 'collapsible', 'ui', 'shadcn'],
    dependencies: ['shadcn-accordion'],
  },
  {
    id: 'dev-alert',
    name: 'Dev Alert',
    description: 'Development-aware alert component',
    componentPath: 'src/lib/dev-container/shadcn/Alert.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Alert.tsx',
    category: 'feedback',
    semanticTags: ['alert', 'notification', 'ui', 'shadcn'],
    dependencies: ['shadcn-alert'],
  },
  {
    id: 'dev-alert-dialog',
    name: 'Dev Alert Dialog',
    description: 'Development-aware alert dialog component',
    componentPath: 'src/lib/dev-container/shadcn/AlertDialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/AlertDialog.tsx',
    category: 'overlay',
    semanticTags: ['dialog', 'alert', 'modal', 'ui', 'shadcn'],
    dependencies: ['shadcn-alert-dialog'],
  },
  {
    id: 'dev-aspect-ratio',
    name: 'Dev Aspect Ratio',
    description: 'Development-aware aspect ratio component',
    componentPath: 'src/lib/dev-container/shadcn/AspectRatio.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/AspectRatio.tsx',
    category: 'layout',
    semanticTags: ['aspect-ratio', 'layout', 'ui', 'shadcn'],
    dependencies: ['shadcn-aspect-ratio'],
  },
  {
    id: 'dev-avatar',
    name: 'Dev Avatar',
    description: 'Development-aware avatar component',
    componentPath: 'src/lib/dev-container/shadcn/Avatar.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Avatar.tsx',
    category: 'data-display',
    semanticTags: ['avatar', 'profile', 'user', 'ui', 'shadcn'],
    dependencies: ['shadcn-avatar'],
  },
  {
    id: 'dev-badge',
    name: 'Dev Badge',
    description: 'Development-aware badge component',
    componentPath: 'src/lib/dev-container/shadcn/Badge.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Badge.tsx',
    category: 'data-display',
    semanticTags: ['badge', 'label', 'ui', 'indicator', 'shadcn'],
    dependencies: ['shadcn-badge'],
    props: {
      variant: ['default', 'secondary', 'destructive', 'outline'],
    },
  },
  {
    id: 'dev-breadcrumb',
    name: 'Dev Breadcrumb',
    description: 'Development-aware breadcrumb component',
    componentPath: 'src/lib/dev-container/shadcn/Breadcrumb.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Breadcrumb.tsx',
    category: 'navigation',
    semanticTags: ['breadcrumb', 'navigation', 'ui', 'shadcn'],
    dependencies: ['shadcn-breadcrumb'],
  },
  {
    id: 'dev-button',
    name: 'Dev Button',
    description: 'Development-aware interactive button component',
    componentPath: 'src/lib/dev-container/shadcn/Button.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Button.tsx',
    category: 'interactive',
    semanticTags: ['button', 'interactive', 'action', 'ui', 'shadcn'],
    dependencies: ['shadcn-button'],
    props: {
      variant: ['default', 'destructive', 'outline', 'secondary', 'ghost', 'link'],
      size: ['default', 'sm', 'lg', 'icon'],
    },
  },
  {
    id: 'dev-calendar',
    name: 'Dev Calendar',
    description: 'Development-aware calendar component',
    componentPath: 'src/lib/dev-container/shadcn/Calendar.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Calendar.tsx',
    category: 'form',
    semanticTags: ['calendar', 'date', 'picker', 'ui', 'shadcn'],
    dependencies: ['shadcn-calendar'],
  },
  {
    id: 'dev-card',
    name: 'Dev Card',
    description: 'Development-aware card component',
    componentPath: 'src/lib/dev-container/shadcn/Card.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Card.tsx',
    category: 'layout',
    semanticTags: ['card', 'container', 'content', 'ui', 'shadcn'],
    dependencies: ['shadcn-card'],
  },
  {
    id: 'dev-card-content',
    name: 'Dev Card Content',
    description: 'Development-aware card content component',
    componentPath: 'src/lib/dev-container/shadcn/Card.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Card.tsx',
    category: 'layout',
    semanticTags: ['card', 'content', 'ui', 'shadcn'],
    dependencies: ['shadcn-card'],
  },
  {
    id: 'dev-carousel',
    name: 'Dev Carousel',
    description: 'Development-aware carousel component',
    componentPath: 'src/lib/dev-container/shadcn/Carousel.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Carousel.tsx',
    category: 'data-display',
    semanticTags: ['carousel', 'slider', 'ui', 'shadcn'],
    dependencies: ['shadcn-carousel'],
  },
  {
    id: 'dev-chart',
    name: 'Dev Chart',
    description: 'Development-aware chart component',
    componentPath: 'src/lib/dev-container/shadcn/Chart.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Chart.tsx',
    category: 'data-display',
    semanticTags: ['chart', 'graph', 'data', 'ui', 'shadcn'],
    dependencies: ['shadcn-chart'],
  },
  {
    id: 'dev-checkbox',
    name: 'Dev Checkbox',
    description: 'Development-aware checkbox component',
    componentPath: 'src/lib/dev-container/shadcn/Checkbox.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Checkbox.tsx',
    category: 'form',
    semanticTags: ['checkbox', 'form', 'input', 'ui', 'shadcn'],
    dependencies: ['shadcn-checkbox'],
  },
  {
    id: 'dev-collapsible',
    name: 'Dev Collapsible',
    description: 'Development-aware collapsible component',
    componentPath: 'src/lib/dev-container/shadcn/Collapsible.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Collapsible.tsx',
    category: 'ui',
    semanticTags: ['collapsible', 'expandable', 'ui', 'shadcn'],
    dependencies: ['shadcn-collapsible'],
  },
  {
    id: 'dev-command',
    name: 'Dev Command',
    description: 'Development-aware command component',
    componentPath: 'src/lib/dev-container/shadcn/Command.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Command.tsx',
    category: 'interactive',
    semanticTags: ['command', 'search', 'ui', 'shadcn'],
    dependencies: ['shadcn-command'],
  },
  {
    id: 'dev-context-menu',
    name: 'Dev Context Menu',
    description: 'Development-aware context menu component',
    componentPath: 'src/lib/dev-container/shadcn/ContextMenu.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/ContextMenu.tsx',
    category: 'overlay',
    semanticTags: ['context-menu', 'menu', 'ui', 'shadcn'],
    dependencies: ['shadcn-context-menu'],
  },
  {
    id: 'dev-dialog',
    name: 'Dev Dialog',
    description: 'Development-aware dialog component',
    componentPath: 'src/lib/dev-container/shadcn/Dialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Dialog.tsx',
    category: 'overlay',
    semanticTags: ['dialog', 'modal', 'ui', 'shadcn'],
    dependencies: ['shadcn-dialog'],
  },
  {
    id: 'dev-drawer',
    name: 'Dev Drawer',
    description: 'Development-aware drawer component',
    componentPath: 'src/lib/dev-container/shadcn/Drawer.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Drawer.tsx',
    category: 'overlay',
    semanticTags: ['drawer', 'sidebar', 'ui', 'shadcn'],
    dependencies: ['shadcn-drawer'],
  },
  {
    id: 'dev-dropdown-menu',
    name: 'Dev Dropdown Menu',
    description: 'Development-aware dropdown menu component',
    componentPath: 'src/lib/dev-container/shadcn/DropdownMenu.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/DropdownMenu.tsx',
    category: 'overlay',
    semanticTags: ['dropdown', 'menu', 'ui', 'shadcn'],
    dependencies: ['shadcn-dropdown-menu'],
  },
  {
    id: 'dev-form',
    name: 'Dev Form',
    description: 'Development-aware form component',
    componentPath: 'src/lib/dev-container/shadcn/Form.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Form.tsx',
    category: 'form',
    semanticTags: ['form', 'input', 'ui', 'shadcn'],
    dependencies: ['shadcn-form'],
  },
  {
    id: 'dev-hover-card',
    name: 'Dev Hover Card',
    description: 'Development-aware hover card component',
    componentPath: 'src/lib/dev-container/shadcn/HoverCard.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/HoverCard.tsx',
    category: 'overlay',
    semanticTags: ['hover-card', 'tooltip', 'ui', 'shadcn'],
    dependencies: ['shadcn-hover-card'],
  },
  {
    id: 'dev-input',
    name: 'Dev Input',
    description: 'Development-aware input component',
    componentPath: 'src/lib/dev-container/shadcn/Input.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Input.tsx',
    category: 'form',
    semanticTags: ['input', 'form', 'ui', 'shadcn'],
    dependencies: ['shadcn-input'],
  },
  {
    id: 'dev-input-otp',
    name: 'Dev Input OTP',
    description: 'Development-aware OTP input component',
    componentPath: 'src/lib/dev-container/shadcn/InputOTP.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/InputOTP.tsx',
    category: 'form',
    semanticTags: ['input', 'otp', 'form', 'ui', 'shadcn'],
    dependencies: ['shadcn-input-otp'],
  },
  {
    id: 'dev-label',
    name: 'Dev Label',
    description: 'Development-aware label component',
    componentPath: 'src/lib/dev-container/shadcn/Label.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Label.tsx',
    category: 'form',
    semanticTags: ['label', 'form', 'ui', 'shadcn'],
    dependencies: ['shadcn-label'],
  },
  {
    id: 'dev-menubar',
    name: 'Dev Menubar',
    description: 'Development-aware menubar component',
    componentPath: 'src/lib/dev-container/shadcn/Menubar.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Menubar.tsx',
    category: 'navigation',
    semanticTags: ['menubar', 'menu', 'navigation', 'ui', 'shadcn'],
    dependencies: ['shadcn-menubar'],
  },
  {
    id: 'dev-navigation-menu',
    name: 'Dev Navigation Menu',
    description: 'Development-aware navigation menu component',
    componentPath: 'src/lib/dev-container/shadcn/NavigationMenu.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/NavigationMenu.tsx',
    category: 'navigation',
    semanticTags: ['navigation', 'menu', 'ui', 'shadcn'],
    dependencies: ['shadcn-navigation-menu'],
  },
  {
    id: 'dev-pagination',
    name: 'Dev Pagination',
    description: 'Development-aware pagination component',
    componentPath: 'src/lib/dev-container/shadcn/Pagination.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Pagination.tsx',
    category: 'navigation',
    semanticTags: ['pagination', 'navigation', 'ui', 'shadcn'],
    dependencies: ['shadcn-pagination'],
  },
  {
    id: 'dev-progress',
    name: 'Dev Progress',
    description: 'Development-aware progress component',
    componentPath: 'src/lib/dev-container/shadcn/Progress.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Progress.tsx',
    category: 'feedback',
    semanticTags: ['progress', 'loading', 'ui', 'shadcn'],
    dependencies: ['shadcn-progress'],
  },
  {
    id: 'dev-radio-group',
    name: 'Dev Radio Group',
    description: 'Development-aware radio group component',
    componentPath: 'src/lib/dev-container/shadcn/RadioGroup.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/RadioGroup.tsx',
    category: 'form',
    semanticTags: ['radio', 'group', 'form', 'ui', 'shadcn'],
    dependencies: ['shadcn-radio-group'],
  },
  {
    id: 'dev-resizable',
    name: 'Dev Resizable',
    description: 'Development-aware resizable component',
    componentPath: 'src/lib/dev-container/shadcn/Resizable.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Resizable.tsx',
    category: 'layout',
    semanticTags: ['resizable', 'layout', 'ui', 'shadcn'],
    dependencies: ['shadcn-resizable'],
  },
  {
    id: 'dev-scroll-area',
    name: 'Dev Scroll Area',
    description: 'Development-aware scroll area component',
    componentPath: 'src/lib/dev-container/shadcn/ScrollArea.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/ScrollArea.tsx',
    category: 'layout',
    semanticTags: ['scroll', 'area', 'layout', 'ui', 'shadcn'],
    dependencies: ['shadcn-scroll-area'],
  },
  {
    id: 'dev-select',
    name: 'Dev Select',
    description: 'Development-aware select component',
    componentPath: 'src/lib/dev-container/shadcn/Select.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Select.tsx',
    category: 'form',
    semanticTags: ['select', 'dropdown', 'form', 'ui', 'shadcn'],
    dependencies: ['shadcn-select'],
  },
  {
    id: 'dev-separator',
    name: 'Dev Separator',
    description: 'Development-aware separator component',
    componentPath: 'src/lib/dev-container/shadcn/Separator.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Separator.tsx',
    category: 'layout',
    semanticTags: ['separator', 'divider', 'ui', 'shadcn'],
    dependencies: ['shadcn-separator'],
  },
  {
    id: 'dev-sheet',
    name: 'Dev Sheet',
    description: 'Development-aware sheet component',
    componentPath: 'src/lib/dev-container/shadcn/Sheet.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Sheet.tsx',
    category: 'overlay',
    semanticTags: ['sheet', 'drawer', 'overlay', 'ui', 'shadcn'],
    dependencies: ['shadcn-sheet'],
  },
  {
    id: 'dev-skeleton',
    name: 'Dev Skeleton',
    description: 'Development-aware skeleton component',
    componentPath: 'src/lib/dev-container/shadcn/Skeleton.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Skeleton.tsx',
    category: 'feedback',
    semanticTags: ['skeleton', 'loading', 'placeholder', 'ui', 'shadcn'],
    dependencies: ['shadcn-skeleton'],
  },
  {
    id: 'dev-slider',
    name: 'Dev Slider',
    description: 'Development-aware slider component',
    componentPath: 'src/lib/dev-container/shadcn/Slider.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Slider.tsx',
    category: 'form',
    semanticTags: ['slider', 'range', 'form', 'ui', 'shadcn'],
    dependencies: ['shadcn-slider'],
  },
  {
    id: 'dev-sonner',
    name: 'Dev Sonner',
    description: 'Development-aware sonner toast component',
    componentPath: 'src/lib/dev-container/shadcn/Sonner.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Sonner.tsx',
    category: 'feedback',
    semanticTags: ['toast', 'notification', 'sonner', 'ui', 'shadcn'],
    dependencies: ['shadcn-sonner'],
  },
  {
    id: 'dev-switch',
    name: 'Dev Switch',
    description: 'Development-aware switch component',
    componentPath: 'src/lib/dev-container/shadcn/Switch.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Switch.tsx',
    category: 'form',
    semanticTags: ['switch', 'toggle', 'form', 'ui', 'shadcn'],
    dependencies: ['shadcn-switch'],
  },
  {
    id: 'dev-table',
    name: 'Dev Table',
    description: 'Development-aware table component',
    componentPath: 'src/lib/dev-container/shadcn/Table.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Table.tsx',
    category: 'data-display',
    semanticTags: ['table', 'data', 'grid', 'ui', 'shadcn'],
    dependencies: ['shadcn-table'],
  },
  {
    id: 'dev-tabs',
    name: 'Dev Tabs',
    description: 'Development-aware tabs component',
    componentPath: 'src/lib/dev-container/shadcn/Tabs.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Tabs.tsx',
    category: 'navigation',
    semanticTags: ['tabs', 'navigation', 'ui', 'shadcn'],
    dependencies: ['shadcn-tabs'],
  },
  {
    id: 'dev-textarea',
    name: 'Dev Textarea',
    description: 'Development-aware textarea component',
    componentPath: 'src/lib/dev-container/shadcn/Textarea.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Textarea.tsx',
    category: 'form',
    semanticTags: ['textarea', 'input', 'form', 'ui', 'shadcn'],
    dependencies: ['shadcn-textarea'],
  },
  {
    id: 'dev-toggle',
    name: 'Dev Toggle',
    description: 'Development-aware toggle component',
    componentPath: 'src/lib/dev-container/shadcn/Toggle.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Toggle.tsx',
    category: 'form',
    semanticTags: ['toggle', 'button', 'ui', 'shadcn'],
    dependencies: ['shadcn-toggle'],
  },
  {
    id: 'dev-toggle-group',
    name: 'Dev Toggle Group',
    description: 'Development-aware toggle group component',
    componentPath: 'src/lib/dev-container/shadcn/ToggleGroup.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/ToggleGroup.tsx',
    category: 'form',
    semanticTags: ['toggle', 'group', 'ui', 'shadcn'],
    dependencies: ['shadcn-toggle-group'],
  },
  {
    id: 'dev-tooltip',
    name: 'Dev Tooltip',
    description: 'Development-aware tooltip component',
    componentPath: 'src/lib/dev-container/shadcn/Tooltip.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Tooltip.tsx',
    category: 'overlay',
    semanticTags: ['tooltip', 'hover', 'ui', 'shadcn'],
    dependencies: ['shadcn-tooltip'],
  },
  {
    id: 'dev-popover',
    name: 'Dev Popover',
    description: 'Development-aware popover component',
    componentPath: 'src/lib/dev-container/shadcn/Popover.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Popover.tsx',
    category: 'overlay',
    semanticTags: ['popover', 'overlay', 'ui', 'shadcn'],
    dependencies: ['shadcn-popover'],
  },
  {
    id: 'dev-sidebar',
    name: 'Dev Sidebar',
    description: 'Development-aware sidebar component',
    componentPath: 'src/lib/dev-container/shadcn/Sidebar.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Sidebar.tsx',
    category: 'layout',
    semanticTags: ['sidebar', 'navigation', 'ui', 'shadcn'],
    dependencies: ['shadcn-sidebar'],
  },

  // Alert sub-components
  {
    id: 'dev-alert-title',
    name: 'Dev Alert Title',
    description: 'Development-aware alert title component',
    componentPath: 'src/lib/dev-container/shadcn/Alert.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Alert.tsx',
    category: 'feedback',
    semanticTags: ['alert', 'title', 'ui', 'shadcn'],
    dependencies: ['shadcn-alert'],
  },
  {
    id: 'dev-alert-description',
    name: 'Dev Alert Description',
    description: 'Development-aware alert description component',
    componentPath: 'src/lib/dev-container/shadcn/Alert.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Alert.tsx',
    category: 'feedback',
    semanticTags: ['alert', 'description', 'ui', 'shadcn'],
    dependencies: ['shadcn-alert'],
  },

  // AlertDialog sub-components
  {
    id: 'dev-alert-dialog-portal',
    name: 'Dev Alert Dialog Portal',
    description: 'Development-aware alert dialog portal component',
    componentPath: 'src/lib/dev-container/shadcn/AlertDialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/AlertDialog.tsx',
    category: 'overlay',
    semanticTags: ['alert-dialog', 'portal', 'ui', 'shadcn'],
    dependencies: ['shadcn-alert-dialog'],
  },
  {
    id: 'dev-alert-dialog-overlay',
    name: 'Dev Alert Dialog Overlay',
    description: 'Development-aware alert dialog overlay component',
    componentPath: 'src/lib/dev-container/shadcn/AlertDialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/AlertDialog.tsx',
    category: 'overlay',
    semanticTags: ['alert-dialog', 'overlay', 'ui', 'shadcn'],
    dependencies: ['shadcn-alert-dialog'],
  },
  {
    id: 'dev-alert-dialog-content',
    name: 'Dev Alert Dialog Content',
    description: 'Development-aware alert dialog content component',
    componentPath: 'src/lib/dev-container/shadcn/AlertDialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/AlertDialog.tsx',
    category: 'overlay',
    semanticTags: ['alert-dialog', 'content', 'ui', 'shadcn'],
    dependencies: ['shadcn-alert-dialog'],
  },
  {
    id: 'dev-alert-dialog-header',
    name: 'Dev Alert Dialog Header',
    description: 'Development-aware alert dialog header component',
    componentPath: 'src/lib/dev-container/shadcn/AlertDialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/AlertDialog.tsx',
    category: 'overlay',
    semanticTags: ['alert-dialog', 'header', 'ui', 'shadcn'],
    dependencies: ['shadcn-alert-dialog'],
  },
  {
    id: 'dev-alert-dialog-footer',
    name: 'Dev Alert Dialog Footer',
    description: 'Development-aware alert dialog footer component',
    componentPath: 'src/lib/dev-container/shadcn/AlertDialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/AlertDialog.tsx',
    category: 'overlay',
    semanticTags: ['alert-dialog', 'footer', 'ui', 'shadcn'],
    dependencies: ['shadcn-alert-dialog'],
  },
  {
    id: 'dev-alert-dialog-title',
    name: 'Dev Alert Dialog Title',
    description: 'Development-aware alert dialog title component',
    componentPath: 'src/lib/dev-container/shadcn/AlertDialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/AlertDialog.tsx',
    category: 'overlay',
    semanticTags: ['alert-dialog', 'title', 'ui', 'shadcn'],
    dependencies: ['shadcn-alert-dialog'],
  },
  {
    id: 'dev-alert-dialog-description',
    name: 'Dev Alert Dialog Description',
    description: 'Development-aware alert dialog description component',
    componentPath: 'src/lib/dev-container/shadcn/AlertDialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/AlertDialog.tsx',
    category: 'overlay',
    semanticTags: ['alert-dialog', 'description', 'ui', 'shadcn'],
    dependencies: ['shadcn-alert-dialog'],
  },
  {
    id: 'dev-alert-dialog-action',
    name: 'Dev Alert Dialog Action',
    description: 'Development-aware alert dialog action component',
    componentPath: 'src/lib/dev-container/shadcn/AlertDialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/AlertDialog.tsx',
    category: 'overlay',
    semanticTags: ['alert-dialog', 'action', 'ui', 'shadcn'],
    dependencies: ['shadcn-alert-dialog'],
  },
  {
    id: 'dev-alert-dialog-cancel',
    name: 'Dev Alert Dialog Cancel',
    description: 'Development-aware alert dialog cancel component',
    componentPath: 'src/lib/dev-container/shadcn/AlertDialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/AlertDialog.tsx',
    category: 'overlay',
    semanticTags: ['alert-dialog', 'cancel', 'ui', 'shadcn'],
    dependencies: ['shadcn-alert-dialog'],
  },

  // Table sub-components
  {
    id: 'dev-table-header',
    name: 'Dev Table Header',
    description: 'Development-aware table header component',
    componentPath: 'src/lib/dev-container/shadcn/Table.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Table.tsx',
    category: 'data-display',
    semanticTags: ['table', 'header', 'ui', 'shadcn'],
    dependencies: ['shadcn-table'],
  },
  {
    id: 'dev-table-body',
    name: 'Dev Table Body',
    description: 'Development-aware table body component',
    componentPath: 'src/lib/dev-container/shadcn/Table.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Table.tsx',
    category: 'data-display',
    semanticTags: ['table', 'body', 'ui', 'shadcn'],
    dependencies: ['shadcn-table'],
  },
  {
    id: 'dev-table-footer',
    name: 'Dev Table Footer',
    description: 'Development-aware table footer component',
    componentPath: 'src/lib/dev-container/shadcn/Table.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Table.tsx',
    category: 'data-display',
    semanticTags: ['table', 'footer', 'ui', 'shadcn'],
    dependencies: ['shadcn-table'],
  },
  {
    id: 'dev-table-row',
    name: 'Dev Table Row',
    description: 'Development-aware table row component',
    componentPath: 'src/lib/dev-container/shadcn/Table.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Table.tsx',
    category: 'data-display',
    semanticTags: ['table', 'row', 'ui', 'shadcn'],
    dependencies: ['shadcn-table'],
  },
  {
    id: 'dev-table-head',
    name: 'Dev Table Head',
    description: 'Development-aware table head component',
    componentPath: 'src/lib/dev-container/shadcn/Table.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Table.tsx',
    category: 'data-display',
    semanticTags: ['table', 'head', 'ui', 'shadcn'],
    dependencies: ['shadcn-table'],
  },
  {
    id: 'dev-table-cell',
    name: 'Dev Table Cell',
    description: 'Development-aware table cell component',
    componentPath: 'src/lib/dev-container/shadcn/Table.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Table.tsx',
    category: 'data-display',
    semanticTags: ['table', 'cell', 'ui', 'shadcn'],
    dependencies: ['shadcn-table'],
  },
  {
    id: 'dev-table-caption',
    name: 'Dev Table Caption',
    description: 'Development-aware table caption component',
    componentPath: 'src/lib/dev-container/shadcn/Table.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Table.tsx',
    category: 'data-display',
    semanticTags: ['table', 'caption', 'ui', 'shadcn'],
    dependencies: ['shadcn-table'],
  },

  // Tabs sub-components
  {
    id: 'dev-tabs-list',
    name: 'Dev Tabs List',
    description: 'Development-aware tabs list component',
    componentPath: 'src/lib/dev-container/shadcn/Tabs.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Tabs.tsx',
    category: 'navigation',
    semanticTags: ['tabs', 'list', 'ui', 'shadcn'],
    dependencies: ['shadcn-tabs'],
  },
  {
    id: 'dev-tabs-trigger',
    name: 'Dev Tabs Trigger',
    description: 'Development-aware tabs trigger component',
    componentPath: 'src/lib/dev-container/shadcn/Tabs.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Tabs.tsx',
    category: 'navigation',
    semanticTags: ['tabs', 'trigger', 'ui', 'shadcn'],
    dependencies: ['shadcn-tabs'],
  },
  {
    id: 'dev-tabs-content',
    name: 'Dev Tabs Content',
    description: 'Development-aware tabs content component',
    componentPath: 'src/lib/dev-container/shadcn/Tabs.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Tabs.tsx',
    category: 'navigation',
    semanticTags: ['tabs', 'content', 'ui', 'shadcn'],
    dependencies: ['shadcn-tabs'],
  },

  // Toggle group sub-components
  {
    id: 'dev-toggle-group-item',
    name: 'Dev Toggle Group Item',
    description: 'Development-aware toggle group item component',
    componentPath: 'src/lib/dev-container/shadcn/ToggleGroup.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/ToggleGroup.tsx',
    category: 'form',
    semanticTags: ['toggle', 'group', 'item', 'ui', 'shadcn'],
    dependencies: ['shadcn-toggle-group'],
  },

  // Tooltip sub-components
  {
    id: 'dev-tooltip-provider',
    name: 'Dev Tooltip Provider',
    description: 'Development-aware tooltip provider component',
    componentPath: 'src/lib/dev-container/shadcn/Tooltip.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Tooltip.tsx',
    category: 'overlay',
    semanticTags: ['tooltip', 'provider', 'ui', 'shadcn'],
    dependencies: ['shadcn-tooltip'],
  },
  {
    id: 'dev-tooltip-trigger',
    name: 'Dev Tooltip Trigger',
    description: 'Development-aware tooltip trigger component',
    componentPath: 'src/lib/dev-container/shadcn/Tooltip.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Tooltip.tsx',
    category: 'overlay',
    semanticTags: ['tooltip', 'trigger', 'ui', 'shadcn'],
    dependencies: ['shadcn-tooltip'],
  },
  {
    id: 'dev-tooltip-content',
    name: 'Dev Tooltip Content',
    description: 'Development-aware tooltip content component',
    componentPath: 'src/lib/dev-container/shadcn/Tooltip.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Tooltip.tsx',
    category: 'overlay',
    semanticTags: ['tooltip', 'content', 'ui', 'shadcn'],
    dependencies: ['shadcn-tooltip'],
  },

  // Additional missing component sub-parts
  {
    id: 'dev-alert-dialog-trigger',
    name: 'Dev Alert Dialog Trigger',
    description: 'Development-aware alert dialog trigger component',
    componentPath: 'src/lib/dev-container/shadcn/AlertDialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/AlertDialog.tsx',
    category: 'overlay',
    semanticTags: ['alert-dialog', 'trigger', 'ui', 'shadcn'],
    dependencies: ['shadcn-alert-dialog'],
  },
  {
    id: 'dev-avatar-image',
    name: 'Dev Avatar Image',
    description: 'Development-aware avatar image component',
    componentPath: 'src/lib/dev-container/shadcn/Avatar.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Avatar.tsx',
    category: 'data-display',
    semanticTags: ['avatar', 'image', 'ui', 'shadcn'],
    dependencies: ['shadcn-avatar'],
  },
  {
    id: 'dev-avatar-fallback',
    name: 'Dev Avatar Fallback',
    description: 'Development-aware avatar fallback component',
    componentPath: 'src/lib/dev-container/shadcn/Avatar.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Avatar.tsx',
    category: 'data-display',
    semanticTags: ['avatar', 'fallback', 'ui', 'shadcn'],
    dependencies: ['shadcn-avatar'],
  },
  {
    id: 'dev-breadcrumb-list',
    name: 'Dev Breadcrumb List',
    description: 'Development-aware breadcrumb list component',
    componentPath: 'src/lib/dev-container/shadcn/Breadcrumb.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Breadcrumb.tsx',
    category: 'navigation',
    semanticTags: ['breadcrumb', 'list', 'ui', 'shadcn'],
    dependencies: ['shadcn-breadcrumb'],
  },
  {
    id: 'dev-breadcrumb-item',
    name: 'Dev Breadcrumb Item',
    description: 'Development-aware breadcrumb item component',
    componentPath: 'src/lib/dev-container/shadcn/Breadcrumb.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Breadcrumb.tsx',
    category: 'navigation',
    semanticTags: ['breadcrumb', 'item', 'ui', 'shadcn'],
    dependencies: ['shadcn-breadcrumb'],
  },
  {
    id: 'dev-breadcrumb-link',
    name: 'Dev Breadcrumb Link',
    description: 'Development-aware breadcrumb link component',
    componentPath: 'src/lib/dev-container/shadcn/Breadcrumb.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Breadcrumb.tsx',
    category: 'navigation',
    semanticTags: ['breadcrumb', 'link', 'ui', 'shadcn'],
    dependencies: ['shadcn-breadcrumb'],
  },
  {
    id: 'dev-breadcrumb-page',
    name: 'Dev Breadcrumb Page',
    description: 'Development-aware breadcrumb page component',
    componentPath: 'src/lib/dev-container/shadcn/Breadcrumb.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcrumb.tsx',
    category: 'navigation',
    semanticTags: ['breadcrumb', 'page', 'ui', 'shadcn'],
    dependencies: ['shadcn-breadcrumb'],
  },
  {
    id: 'dev-breadcrumb-separator',
    name: 'Dev Breadcrumb Separator',
    description: 'Development-aware breadcrumb separator component',
    componentPath: 'src/lib/dev-container/shadcn/Breadcrumb.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Breadcrumb.tsx',
    category: 'navigation',
    semanticTags: ['breadcrumb', 'separator', 'ui', 'shadcn'],
    dependencies: ['shadcn-breadcrumb'],
  },
  {
    id: 'dev-breadcrumb-ellipsis',
    name: 'Dev Breadcrumb Ellipsis',
    description: 'Development-aware breadcrumb ellipsis component',
    componentPath: 'src/lib/dev-container/shadcn/Breadcrumb.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Breadcrumb.tsx',
    category: 'navigation',
    semanticTags: ['breadcrumb', 'ellipsis', 'ui', 'shadcn'],
    dependencies: ['shadcn-breadcrumb'],
  },
  {
    id: 'dev-card-header',
    name: 'Dev Card Header',
    description: 'Development-aware card header component',
    componentPath: 'src/lib/dev-container/shadcn/Card.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Card.tsx',
    category: 'layout',
    semanticTags: ['card', 'header', 'ui', 'shadcn'],
    dependencies: ['shadcn-card'],
  },
  {
    id: 'dev-card-title',
    name: 'Dev Card Title',
    description: 'Development-aware card title component',
    componentPath: 'src/lib/dev-container/shadcn/Card.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Card.tsx',
    category: 'layout',
    semanticTags: ['card', 'title', 'ui', 'shadcn'],
    dependencies: ['shadcn-card'],
  },
  {
    id: 'dev-card-description',
    name: 'Dev Card Description',
    description: 'Development-aware card description component',
    componentPath: 'src/lib/dev-container/shadcn/Card.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Card.tsx',
    category: 'layout',
    semanticTags: ['card', 'description', 'ui', 'shadcn'],
    dependencies: ['shadcn-card'],
  },
  {
    id: 'dev-card-footer',
    name: 'Dev Card Footer',
    description: 'Development-aware card footer component',
    componentPath: 'src/lib/dev-container/shadcn/Card.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Card.tsx',
    category: 'layout',
    semanticTags: ['card', 'footer', 'ui', 'shadcn'],
    dependencies: ['shadcn-card'],
  },
  {
    id: 'dev-carousel-content',
    name: 'Dev Carousel Content',
    description: 'Development-aware carousel content component',
    componentPath: 'src/lib/dev-container/shadcn/Carousel.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Carousel.tsx',
    category: 'data-display',
    semanticTags: ['carousel', 'content', 'ui', 'shadcn'],
    dependencies: ['shadcn-carousel'],
  },
  {
    id: 'dev-carousel-item',
    name: 'Dev Carousel Item',
    description: 'Development-aware carousel item component',
    componentPath: 'src/lib/dev-container/shadcn/Carousel.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Carousel.tsx',
    category: 'data-display',
    semanticTags: ['carousel', 'item', 'ui', 'shadcn'],
    dependencies: ['shadcn-carousel'],
  },
  {
    id: 'dev-carousel-previous',
    name: 'Dev Carousel Previous',
    description: 'Development-aware carousel previous button component',
    componentPath: 'src/lib/dev-container/shadcn/Carousel.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Carousel.tsx',
    category: 'data-display',
    semanticTags: ['carousel', 'previous', 'ui', 'shadcn'],
    dependencies: ['shadcn-carousel'],
  },
  {
    id: 'dev-carousel-next',
    name: 'Dev Carousel Next',
    description: 'Development-aware carousel next button component',
    componentPath: 'src/lib/dev-container/shadcn/Carousel.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Carousel.tsx',
    category: 'data-display',
    semanticTags: ['carousel', 'next', 'ui', 'shadcn'],
    dependencies: ['shadcn-carousel'],
  },
  {
    id: 'dev-toaster',
    name: 'Dev Toaster',
    description: 'Development-aware toaster component',
    componentPath: 'src/lib/dev-container/shadcn/Sonner.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Sonner.tsx',
    category: 'feedback',
    semanticTags: ['toaster', 'notification', 'ui', 'shadcn'],
    dependencies: ['shadcn-sonner'],
  },
  {
    id: 'dev-sidebar-provider',
    name: 'Dev Sidebar Provider',
    description: 'Development-aware sidebar provider component',
    componentPath: 'src/lib/dev-container/shadcn/Sidebar.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Sidebar.tsx',
    category: 'layout',
    semanticTags: ['sidebar', 'provider', 'ui', 'shadcn'],
    dependencies: ['shadcn-sidebar'],
  },
  {
    id: 'dev-sidebar-trigger',
    name: 'Dev Sidebar Trigger',
    description: 'Development-aware sidebar trigger component',
    componentPath: 'src/lib/dev-container/shadcn/Sidebar.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Sidebar.tsx',
    category: 'layout',
    semanticTags: ['sidebar', 'trigger', 'ui', 'shadcn'],
    dependencies: ['shadcn-sidebar'],
  },
  {
    id: 'dev-sidebar-content',
    name: 'Dev Sidebar Content',
    description: 'Development-aware sidebar content component',
    componentPath: 'src/lib/dev-container/shadcn/Sidebar.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Sidebar.tsx',
    category: 'layout',
    semanticTags: ['sidebar', 'content', 'ui', 'shadcn'],
    dependencies: ['shadcn-sidebar'],
  },
  {
    id: 'dev-sidebar-header',
    name: 'Dev Sidebar Header',
    description: 'Development-aware sidebar header component',
    componentPath: 'src/lib/dev-container/shadcn/Sidebar.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Sidebar.tsx',
    category: 'layout',
    semanticTags: ['sidebar', 'header', 'ui', 'shadcn'],
    dependencies: ['shadcn-sidebar'],
  },
  {
    id: 'dev-sidebar-footer',
    name: 'Dev Sidebar Footer',
    description: 'Development-aware sidebar footer component',
    componentPath: 'src/lib/dev-container/shadcn/Sidebar.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Sidebar.tsx',
    category: 'layout',
    semanticTags: ['sidebar', 'footer', 'ui', 'shadcn'],
    dependencies: ['shadcn-sidebar'],
  },
  {
    id: 'dev-sidebar-menu',
    name: 'Dev Sidebar Menu',
    description: 'Development-aware sidebar menu component',
    componentPath: 'src/lib/dev-container/shadcn/Sidebar.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Sidebar.tsx',
    category: 'layout',
    semanticTags: ['sidebar', 'menu', 'ui', 'shadcn'],
    dependencies: ['shadcn-sidebar'],
  },
  {
    id: 'dev-sidebar-menu-item',
    name: 'Dev Sidebar Menu Item',
    description: 'Development-aware sidebar menu item component',
    componentPath: 'src/lib/dev-container/shadcn/Sidebar.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Sidebar.tsx',
    category: 'layout',
    semanticTags: ['sidebar', 'menu', 'item', 'ui', 'shadcn'],
    dependencies: ['shadcn-sidebar'],
  },
  {
    id: 'dev-sidebar-menu-button',
    name: 'Dev Sidebar Menu Button',
    description: 'Development-aware sidebar menu button component',
    componentPath: 'src/lib/dev-container/shadcn/Sidebar.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Sidebar.tsx',
    category: 'layout',
    semanticTags: ['sidebar', 'menu', 'button', 'ui', 'shadcn'],
    dependencies: ['shadcn-sidebar'],
  },

  // =====================================
  // GEENIUS COMPONENTS
  // =====================================
  {
    id: 'dev-div',
    name: 'Dev Div',
    description: 'Development-aware div container element',
    componentPath: 'src/lib/dev-container/geenius/Div.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Div.tsx',
    category: 'layout',
    semanticTags: ['div', 'container', 'layout', 'wrapper'],
  },
  {
    id: 'dev-footer',
    name: 'Dev Footer',
    description: 'Development-aware footer element',
    componentPath: 'src/lib/dev-container/geenius/Footer.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Footer.tsx',
    category: 'layout',
    semanticTags: ['footer', 'navigation', 'layout'],
  },
  {
    id: 'dev-header',
    name: 'Dev Header',
    description: 'Development-aware header element',
    componentPath: 'src/lib/dev-container/geenius/Header.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Header.tsx',
    category: 'layout',
    semanticTags: ['header', 'top', 'semantic'],
  },
  {
    id: 'dev-h1',
    name: 'Dev H1',
    description: 'Development-aware H1 heading element',
    componentPath: 'src/lib/dev-container/geenius/Headings.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Headings.tsx',
    category: 'typography',
    semanticTags: ['h1', 'heading', 'title', 'content'],
  },
  {
    id: 'dev-h2',
    name: 'Dev H2',
    description: 'Development-aware H2 heading element',
    componentPath: 'src/lib/dev-container/geenius/Headings.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Headings.tsx',
    category: 'typography',
    semanticTags: ['h2', 'heading', 'subtitle', 'content'],
  },
  {
    id: 'dev-h3',
    name: 'Dev H3',
    description: 'Development-aware H3 heading element',
    componentPath: 'src/lib/dev-container/geenius/Headings.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Headings.tsx',
    category: 'typography',
    semanticTags: ['h3', 'heading', 'section-title', 'content'],
  },
  {
    id: 'dev-h4',
    name: 'Dev H4',
    description: 'Development-aware H4 heading element',
    componentPath: 'src/lib/dev-container/geenius/Headings.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Headings.tsx',
    category: 'typography',
    semanticTags: ['h4', 'heading', 'subsection-title', 'content'],
  },
  {
    id: 'dev-h5',
    name: 'Dev H5',
    description: 'Development-aware H5 heading element',
    componentPath: 'src/lib/dev-container/geenius/Headings.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Headings.tsx',
    category: 'typography',
    semanticTags: ['h5', 'heading', 'minor-title', 'content'],
  },
  {
    id: 'dev-h6',
    name: 'Dev H6',
    description: 'Development-aware H6 heading element',
    componentPath: 'src/lib/dev-container/geenius/Headings.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Headings.tsx',
    category: 'typography',
    semanticTags: ['h6', 'heading', 'smallest-title', 'content'],
  },
  {
    id: 'dev-ul',
    name: 'Dev Unordered List',
    description: 'Development-aware unordered list element',
    componentPath: 'src/lib/dev-container/geenius/Lists.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Lists.tsx',
    category: 'content',
    semanticTags: ['ul', 'list', 'unordered', 'content'],
  },
  {
    id: 'dev-ol',
    name: 'Dev Ordered List',
    description: 'Development-aware ordered list element',
    componentPath: 'src/lib/dev-container/geenius/Lists.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Lists.tsx',
    category: 'content',
    semanticTags: ['ol', 'list', 'ordered', 'numbered', 'content'],
  },
  {
    id: 'dev-li',
    name: 'Dev List Item',
    description: 'Development-aware list item element',
    componentPath: 'src/lib/dev-container/geenius/Lists.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Lists.tsx',
    category: 'content',
    semanticTags: ['li', 'list-item', 'item', 'content'],
  },
  {
    id: 'dev-img',
    name: 'Dev Image',
    description: 'Development-aware image element',
    componentPath: 'src/lib/dev-container/geenius/Media.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Media.tsx',
    category: 'media',
    semanticTags: ['img', 'image', 'media', 'content'],
  },
  {
    id: 'dev-video',
    name: 'Dev Video',
    description: 'Development-aware video element',
    componentPath: 'src/lib/dev-container/geenius/Media.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Media.tsx',
    category: 'media',
    semanticTags: ['video', 'media', 'player', 'content'],
  },
  {
    id: 'dev-audio',
    name: 'Dev Audio',
    description: 'Development-aware audio element',
    componentPath: 'src/lib/dev-container/geenius/Media.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Media.tsx',
    category: 'media',
    semanticTags: ['audio', 'media', 'player', 'content'],
  },
  {
    id: 'dev-nav',
    name: 'Dev Nav',
    description: 'Development-aware navigation element',
    componentPath: 'src/lib/dev-container/geenius/Nav.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Nav.tsx',
    category: 'navigation',
    semanticTags: ['nav', 'navigation', 'menu', 'layout'],
  },
  {
    id: 'dev-p',
    name: 'Dev Paragraph',
    description: 'Development-aware paragraph element',
    componentPath: 'src/lib/dev-container/geenius/Paragraph.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Paragraph.tsx',
    category: 'typography',
    semanticTags: ['p', 'paragraph', 'text', 'content'],
  },
  {
    id: 'dev-section',
    name: 'Dev Section',
    description: 'Development-aware section element',
    componentPath: 'src/lib/dev-container/geenius/Section.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Section.tsx',
    category: 'layout',
    semanticTags: ['section', 'content', 'layout'],
  },
  {
    id: 'dev-article',
    name: 'Dev Article',
    description: 'Development-aware article element',
    componentPath: 'src/lib/dev-container/geenius/Semantic.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Semantic.tsx',
    category: 'content',
    semanticTags: ['article', 'content', 'layout'],
  },
  {
    id: 'dev-aside',
    name: 'Dev Aside',
    description: 'Development-aware aside element',
    componentPath: 'src/lib/dev-container/geenius/Semantic.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Semantic.tsx',
    category: 'content',
    semanticTags: ['aside', 'sidebar', 'layout'],
  },
  {
    id: 'dev-main',
    name: 'Dev Main',
    description: 'Development-aware main element',
    componentPath: 'src/lib/dev-container/geenius/Semantic.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Semantic.tsx',
    category: 'layout',
    semanticTags: ['main', 'content', 'layout'],
  },
  // Add these component definitions to your componentLibrary.ts file:

  // =====================================
  // ADDITIONAL GEENIUS COMPONENTS (add to existing geenius section)
  // =====================================
  {
    id: 'dev-figure',
    name: 'Dev Figure',
    description: 'Development-aware figure element for media content',
    componentPath: 'src/lib/dev-container/geenius/Semantic.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Semantic.tsx',
    category: 'media',
    semanticTags: ['figure', 'media', 'semantic', 'content'],
  },
  {
    id: 'dev-figcaption',
    name: 'Dev Figcaption',
    description: 'Development-aware figcaption element for figure captions',
    componentPath: 'src/lib/dev-container/geenius/Semantic.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Semantic.tsx',
    category: 'typography',
    semanticTags: ['figcaption', 'caption', 'semantic', 'content'],
  },
  {
    id: 'dev-anchor',
    name: 'Dev Anchor',
    description: 'Development-aware anchor/link element',
    componentPath: 'src/lib/dev-container/geenius/Text.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Text.tsx',
    category: 'interactive',
    semanticTags: ['a', 'anchor', 'link', 'navigation', 'interactive'],
  },
  {
    id: 'dev-code',
    name: 'Dev Code',
    description: 'Development-aware inline code element',
    componentPath: 'src/lib/dev-container/geenius/Text.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Text.tsx',
    category: 'typography',
    semanticTags: ['code', 'programming', 'inline', 'text', 'semantic'],
  },
  {
    id: 'dev-pre',
    name: 'Dev Pre',
    description: 'Development-aware preformatted text element',
    componentPath: 'src/lib/dev-container/geenius/Text.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Text.tsx',
    category: 'typography',
    semanticTags: ['pre', 'preformatted', 'code-block', 'text', 'semantic'],
  },
  {
    id: 'dev-blockquote',
    name: 'Dev Blockquote',
    description: 'Development-aware blockquote element',
    componentPath: 'src/lib/dev-container/geenius/Text.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Text.tsx',
    category: 'content',
    semanticTags: ['blockquote', 'quote', 'citation', 'text', 'semantic'],
  },
  {
    id: 'dev-span',
    name: 'Dev Span',
    description: 'Development-aware span element',
    componentPath: 'src/lib/dev-container/geenius/Span.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Span.tsx',
    category: 'typography',
    semanticTags: ['span', 'inline', 'text'],
  },
  {
    id: 'dev-small',
    name: 'Dev Small',
    description: 'Development-aware small text element',
    componentPath: 'src/lib/dev-container/geenius/Text.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Text.tsx',
    category: 'typography',
    semanticTags: ['small', 'text', 'fine-print'],
  },
  {
    id: 'dev-strong',
    name: 'Dev Strong',
    description: 'Development-aware strong text element',
    componentPath: 'src/lib/dev-container/geenius/Text.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Text.tsx',
    category: 'typography',
    semanticTags: ['strong', 'text', 'bold'],
  },
  {
    id: 'dev-em',
    name: 'Dev Emphasis',
    description: 'Development-aware emphasis text element',
    componentPath: 'src/lib/dev-container/geenius/Text.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Text.tsx',
    category: 'typography',
    semanticTags: ['em', 'text', 'emphasis', 'italic'],
  },
  {
    id: 'dev-paragraph',
    name: 'Dev Paragraph',
    description: 'Development-aware paragraph element',
    componentPath: 'src/lib/dev-container/geenius/Paragraph.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/geenius/Paragraph.tsx',
    category: 'typography',
    semanticTags: ['p', 'paragraph', 'text', 'content'],
  },

  // Many other missing sub-components
  {
    id: 'dev-accordion-item',
    name: 'Dev Accordion Item',
    description: 'Development-aware accordion item component',
    componentPath: 'src/lib/dev-container/shadcn/Accordion.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Accordion.tsx',
    category: 'ui',
    semanticTags: ['accordion', 'item', 'ui', 'shadcn'],
    dependencies: ['shadcn-accordion'],
  },
  {
    id: 'dev-accordion-trigger',
    name: 'Dev Accordion Trigger',
    description: 'Development-aware accordion trigger component',
    componentPath: 'src/lib/dev-container/shadcn/Accordion.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Accordion.tsx',
    category: 'ui',
    semanticTags: ['accordion', 'trigger', 'ui', 'shadcn'],
    dependencies: ['shadcn-accordion'],
  },
  {
    id: 'dev-accordion-content',
    name: 'Dev Accordion Content',
    description: 'Development-aware accordion content component',
    componentPath: 'src/lib/dev-container/shadcn/Accordion.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Accordion.tsx',
    category: 'ui',
    semanticTags: ['accordion', 'content', 'ui', 'shadcn'],
    dependencies: ['shadcn-accordion'],
  },
  {
    id: 'dev-chart-container',
    name: 'Dev Chart Container',
    description: 'Development-aware chart container component',
    componentPath: 'src/lib/dev-container/shadcn/Chart.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Chart.tsx',
    category: 'data-display',
    semanticTags: ['chart', 'container', 'ui', 'shadcn'],
    dependencies: ['shadcn-chart'],
  },
  {
    id: 'dev-chart-tooltip',
    name: 'Dev Chart Tooltip',
    description: 'Development-aware chart tooltip component',
    componentPath: 'src/lib/dev-container/shadcn/Chart.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Chart.tsx',
    category: 'data-display',
    semanticTags: ['chart', 'tooltip', 'ui', 'shadcn'],
    dependencies: ['shadcn-chart'],
  },
  {
    id: 'dev-chart-tooltip-content',
    name: 'Dev Chart Tooltip Content',
    description: 'Development-aware chart tooltip content component',
    componentPath: 'src/lib/dev-container/shadcn/Chart.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Chart.tsx',
    category: 'data-display',
    semanticTags: ['chart', 'tooltip', 'content', 'ui', 'shadcn'],
    dependencies: ['shadcn-chart'],
  },
  {
    id: 'dev-chart-legend',
    name: 'Dev Chart Legend',
    description: 'Development-aware chart legend component',
    componentPath: 'src/lib/dev-container/shadcn/Chart.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Chart.tsx',
    category: 'data-display',
    semanticTags: ['chart', 'legend', 'ui', 'shadcn'],
    dependencies: ['shadcn-chart'],
  },
  {
    id: 'dev-chart-legend-content',
    name: 'Dev Chart Legend Content',
    description: 'Development-aware chart legend content component',
    componentPath: 'src/lib/dev-container/shadcn/Chart.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Chart.tsx',
    category: 'data-display',
    semanticTags: ['chart', 'legend', 'content', 'ui', 'shadcn'],
    dependencies: ['shadcn-chart'],
  },
  {
    id: 'dev-collapsible-trigger',
    name: 'Dev Collapsible Trigger',
    description: 'Development-aware collapsible trigger component',
    componentPath: 'src/lib/dev-container/shadcn/Collapsible.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Collapsible.tsx',
    category: 'ui',
    semanticTags: ['collapsible', 'trigger', 'ui', 'shadcn'],
    dependencies: ['shadcn-collapsible'],
  },
  {
    id: 'dev-collapsible-content',
    name: 'Dev Collapsible Content',
    description: 'Development-aware collapsible content component',
    componentPath: 'src/lib/dev-container/shadcn/Collapsible.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Collapsible.tsx',
    category: 'ui',
    semanticTags: ['collapsible', 'content', 'ui', 'shadcn'],
    dependencies: ['shadcn-collapsible'],
  },
  {
    id: 'dev-command-input',
    name: 'Dev Command Input',
    description: 'Development-aware command input component',
    componentPath: 'src/lib/dev-container/shadcn/Command.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Command.tsx',
    category: 'interactive',
    semanticTags: ['command', 'input', 'ui', 'shadcn'],
    dependencies: ['shadcn-command'],
  },
  {
    id: 'dev-command-list',
    name: 'Dev Command List',
    description: 'Development-aware command list component',
    componentPath: 'src/lib/dev-container/shadcn/Command.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Command.tsx',
    category: 'interactive',
    semanticTags: ['command', 'list', 'ui', 'shadcn'],
    dependencies: ['shadcn-command'],
  },
  {
    id: 'dev-command-empty',
    name: 'Dev Command Empty',
    description: 'Development-aware command empty component',
    componentPath: 'src/lib/dev-container/shadcn/Command.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Command.tsx',
    category: 'interactive',
    semanticTags: ['command', 'empty', 'ui', 'shadcn'],
    dependencies: ['shadcn-command'],
  },
  {
    id: 'dev-command-group',
    name: 'Dev Command Group',
    description: 'Development-aware command group component',
    componentPath: 'src/lib/dev-container/shadcn/Command.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Command.tsx',
    category: 'interactive',
    semanticTags: ['command', 'group', 'ui', 'shadcn'],
    dependencies: ['shadcn-command'],
  },
  {
    id: 'dev-command-item',
    name: 'Dev Command Item',
    description: 'Development-aware command item component',
    componentPath: 'src/lib/dev-container/shadcn/Command.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Command.tsx',
    category: 'interactive',
    semanticTags: ['command', 'item', 'ui', 'shadcn'],
    dependencies: ['shadcn-command'],
  },
  {
    id: 'dev-command-shortcut',
    name: 'Dev Command Shortcut',
    description: 'Development-aware command shortcut component',
    componentPath: 'src/lib/dev-container/shadcn/Command.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Command.tsx',
    category: 'interactive',
    semanticTags: ['command', 'shortcut', 'ui', 'shadcn'],
    dependencies: ['shadcn-command'],
  },
  {
    id: 'dev-command-separator',
    name: 'Dev Command Separator',
    description: 'Development-aware command separator component',
    componentPath: 'src/lib/dev-container/shadcn/Command.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Command.tsx',
    category: 'interactive',
    semanticTags: ['command', 'separator', 'ui', 'shadcn'],
    dependencies: ['shadcn-command'],
  },

  // =====================================
  // ADDITIONAL MISSING SUB-COMPONENTS
  // =====================================

  // Context Menu sub-components
  {
    id: 'dev-context-menu-trigger',
    name: 'Dev Context Menu Trigger',
    description: 'Development-aware context menu trigger component',
    componentPath: 'src/lib/dev-container/shadcn/ContextMenu.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/ContextMenu.tsx',
    category: 'overlay',
    semanticTags: ['context-menu', 'trigger', 'ui', 'shadcn'],
    dependencies: ['shadcn-context-menu'],
  },
  {
    id: 'dev-context-menu-content',
    name: 'Dev Context Menu Content',
    description: 'Development-aware context menu content component',
    componentPath: 'src/lib/dev-container/shadcn/ContextMenu.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/ContextMenu.tsx',
    category: 'overlay',
    semanticTags: ['context-menu', 'content', 'ui', 'shadcn'],
    dependencies: ['shadcn-context-menu'],
  },
  {
    id: 'dev-context-menu-item',
    name: 'Dev Context Menu Item',
    description: 'Development-aware context menu item component',
    componentPath: 'src/lib/dev-container/shadcn/ContextMenu.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/ContextMenu.tsx',
    category: 'overlay',
    semanticTags: ['context-menu', 'item', 'ui', 'shadcn'],
    dependencies: ['shadcn-context-menu'],
  },
  {
    id: 'dev-context-menu-separator',
    name: 'Dev Context Menu Separator',
    description: 'Development-aware context menu separator component',
    componentPath: 'src/lib/dev-container/shadcn/ContextMenu.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/ContextMenu.tsx',
    category: 'overlay',
    semanticTags: ['context-menu', 'separator', 'ui', 'shadcn'],
    dependencies: ['shadcn-context-menu'],
  },

  // Dialog sub-components
  {
    id: 'dev-dialog-trigger',
    name: 'Dev Dialog Trigger',
    description: 'Development-aware dialog trigger component',
    componentPath: 'src/lib/dev-container/shadcn/Dialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Dialog.tsx',
    category: 'overlay',
    semanticTags: ['dialog', 'trigger', 'ui', 'shadcn'],
    dependencies: ['shadcn-dialog'],
  },
  {
    id: 'dev-dialog-content',
    name: 'Dev Dialog Content',
    description: 'Development-aware dialog content component',
    componentPath: 'src/lib/dev-container/shadcn/Dialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Dialog.tsx',
    category: 'overlay',
    semanticTags: ['dialog', 'content', 'ui', 'shadcn'],
    dependencies: ['shadcn-dialog'],
  },
  {
    id: 'dev-dialog-header',
    name: 'Dev Dialog Header',
    description: 'Development-aware dialog header component',
    componentPath: 'src/lib/dev-container/shadcn/Dialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Dialog.tsx',
    category: 'overlay',
    semanticTags: ['dialog', 'header', 'ui', 'shadcn'],
    dependencies: ['shadcn-dialog'],
  },
  {
    id: 'dev-dialog-footer',
    name: 'Dev Dialog Footer',
    description: 'Development-aware dialog footer component',
    componentPath: 'src/lib/dev-container/shadcn/Dialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Dialog.tsx',
    category: 'overlay',
    semanticTags: ['dialog', 'footer', 'ui', 'shadcn'],
    dependencies: ['shadcn-dialog'],
  },
  {
    id: 'dev-dialog-title',
    name: 'Dev Dialog Title',
    description: 'Development-aware dialog title component',
    componentPath: 'src/lib/dev-container/shadcn/Dialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Dialog.tsx',
    category: 'overlay',
    semanticTags: ['dialog', 'title', 'ui', 'shadcn'],
    dependencies: ['shadcn-dialog'],
  },
  {
    id: 'dev-dialog-description',
    name: 'Dev Dialog Description',
    description: 'Development-aware dialog description component',
    componentPath: 'src/lib/dev-container/shadcn/Dialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Dialog.tsx',
    category: 'overlay',
    semanticTags: ['dialog', 'description', 'ui', 'shadcn'],
    dependencies: ['shadcn-dialog'],
  },
  {
    id: 'dev-dialog-close',
    name: 'Dev Dialog Close',
    description: 'Development-aware dialog close component',
    componentPath: 'src/lib/dev-container/shadcn/Dialog.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/shadcn/Dialog.tsx',
    category: 'overlay',
    semanticTags: ['dialog', 'close', 'ui', 'shadcn'],
    dependencies: ['shadcn-dialog'],
  },

  // =====================================
  // CORE SYSTEM COMPONENTS
  // ===================================
  {
    id: 'dev-container',
    name: 'Dev Container',
    description: 'Core development mode container wrapper for component registration',
    componentPath: 'src/lib/dev-container/components/Container.tsx',
    repositoryPath: 'https://github.com/your-username/geenius-template-vite-react-mongo/blob/main/src/lib/dev-container/components/Container.tsx',
    category: 'layout',
    semanticTags: ['container', 'wrapper', 'dev', 'registration', 'core'],
  },
] as const;


// Extract the literal union type for component IDs
export type ComponentLibraryId = typeof componentDefinitions[number]['id'];

// Create a typed version for runtime use (removes readonly constraint)
export const componentDefinitionsArray: ComponentDefinition[] = componentDefinitions as any;

// Build the component library
export const componentLibrary: ComponentLibrary = componentDefinitionsArray.reduce((library, definition) => {
  library[definition.id] = definition;
  return library;
}, {} as ComponentLibrary);

// Export the const version for type extraction but the regular version for runtime
export { componentDefinitionsArray as componentDefinitions };

// Helper functions (now work with regular ComponentDefinition[])
export const getComponentDefinition = (id: string): ComponentDefinition | undefined => {
  return componentLibrary[id];
};

export const getComponentsByCategory = (category: ComponentCategory): ComponentDefinition[] => {
  return componentDefinitionsArray.filter(def => def.category === category);
};

export const getShadcnComponents = (): ComponentDefinition[] => {
  return componentDefinitionsArray.filter(def => def.semanticTags.includes('shadcn'));
};

export const getGeeniusComponents = (): ComponentDefinition[] => {
  return componentDefinitionsArray.filter(def =>
    def.componentPath.includes('/geenius/') && !def.semanticTags.includes('shadcn')
  );
};

export const searchComponents = (query: string): ComponentDefinition[] => {
  const lowercaseQuery = query.toLowerCase();
  return componentDefinitionsArray.filter(def =>
    def.name.toLowerCase().includes(lowercaseQuery) ||
    def.description.toLowerCase().includes(lowercaseQuery) ||
    def.semanticTags.some(tag => tag.toLowerCase().includes(lowercaseQuery))
  );
}

// Add this at the end of your componentLibrary.ts file
const validation = validateUniqueIds(componentDefinitionsArray);
if (!validation.isValid) {
  throw new Error(`🚨 Duplicate component IDs detected: ${validation.duplicates.join(', ')}`);
}