// src/registry/generatedTypes.ts
// Auto-generated file - DO NOT EDIT DIRECTLY
// Run 'npm run generate-types' to regenerate

// Component IDs union type
export type ComponentRegistryId = 'action-filter-label' | 'activity-card' | 'activity-content' | 'activity-tab' | 'admin-audit-logs-loading' | 'admin-audit-logs-page' | 'admin-dashboard' | 'admin-layout' | 'admin-nav' | 'admin-route-denied' | 'admin-route-loading' | 'app-root' | 'audit-page-button-1' | 'audit-page-button-2' | 'audit-page-button-3' | 'audit-page-button-4' | 'audit-page-button-5' | 'audit-page-button-dynamic' | 'audit-status-badge-dynamic' | 'auth-buttons' | 'back-button' | 'back-link' | 'brand-name' | 'cancel-delete' | 'change-role-button' | 'clear-filters-button' | 'confirm-delete' | 'cta-join-community' | 'cta-section' | 'cta-start-project' | 'current-role-badge' | 'dashboard-content' | 'dashboard-header' | 'dashboard-loading' | 'dashboard-page' | 'dashboard-stats' | 'dashboard-unauthorized' | 'delete-button' | 'delete-confirm-alert' | 'details-card' | 'details-content' | 'details-tab' | 'docs-button' | 'end-date-input' | 'end-date-label' | 'error-alert' | 'error-card' | 'export-button' | 'feature-card-0' | 'feature-card-1' | 'feature-card-2' | 'feature-card-3' | 'features-section' | 'filters-card' | 'hero-content' | 'hero-content-wrapper' | 'hero-cta-buttons' | 'hero-description' | 'hero-github-button' | 'hero-section' | 'hero-start-building' | 'hero-title' | 'landing-page-root' | 'loading-card' | 'login-divider' | 'login-error' | 'login-footer' | 'login-form' | 'login-header' | 'login-page' | 'logo-section' | 'logs-table-card' | 'main-footer' | 'main-header' | 'main-nav' | 'main-wrapper' | 'mongodb-highlight' | 'nav-actions' | 'nav-dashboard-button' | 'nav-login-button' | 'nav-register-button' | 'next-page-button' | 'page-button-1' | 'page-button-2' | 'page-button-3' | 'page-button-4' | 'page-button-5' | 'page-button-dynamic' | 'pagination-card' | 'permissions-card' | 'permissions-content' | 'permissions-tab' | 'prev-page-button' | 'protected-route-loading' | 'register-divider' | 'register-error' | 'register-footer' | 'register-form' | 'register-header' | 'register-page' | 'role-badge' | 'role-badge-dynamic' | 'role-label' | 'search-button' | 'search-input' | 'search-label' | 'sessions-card' | 'sessions-content' | 'sessions-tab' | 'social-login-buttons' | 'social-register-buttons' | 'start-date-input' | 'start-date-label' | 'stat-card-0' | 'stat-card-1' | 'stat-card-2' | 'stat-card-3' | 'stats-content' | 'stats-grid' | 'stats-section' | 'tabs-list' | 'tech-badge-0' | 'tech-badge-1' | 'tech-badge-2' | 'tech-badge-3' | 'tech-badge-4' | 'tech-badge-5' | 'tech-letter-0' | 'tech-letter-1' | 'tech-letter-2' | 'tech-letter-3' | 'tech-letter-4' | 'tech-letter-5' | 'tech-stack-section' | 'user-details-error' | 'user-details-loading' | 'user-details-page' | 'user-filter-label' | 'user-info-card' | 'user-profile-card' | 'user-section' | 'user-tabs' | 'users-filters' | 'users-page' | 'users-table-card' | 'verified-badge' | 'welcome-message' | string;

// Valid component IDs array
export const VALID_COMPONENT_IDS = [
  'action-filter-label',
  'activity-card',
  'activity-content',
  'activity-tab',
  'admin-audit-logs-loading',
  'admin-audit-logs-page',
  'admin-dashboard',
  'admin-layout',
  'admin-nav',
  'admin-route-denied',
  'admin-route-loading',
  'app-root',
  'audit-page-button-1',
  'audit-page-button-2',
  'audit-page-button-3',
  'audit-page-button-4',
  'audit-page-button-5',
  'audit-page-button-dynamic',
  'audit-status-badge-dynamic',
  'auth-buttons',
  'back-button',
  'back-link',
  'brand-name',
  'cancel-delete',
  'change-role-button',
  'clear-filters-button',
  'confirm-delete',
  'cta-join-community',
  'cta-section',
  'cta-start-project',
  'current-role-badge',
  'dashboard-content',
  'dashboard-header',
  'dashboard-loading',
  'dashboard-page',
  'dashboard-stats',
  'dashboard-unauthorized',
  'delete-button',
  'delete-confirm-alert',
  'details-card',
  'details-content',
  'details-tab',
  'docs-button',
  'end-date-input',
  'end-date-label',
  'error-alert',
  'error-card',
  'export-button',
  'feature-card-0',
  'feature-card-1',
  'feature-card-2',
  'feature-card-3',
  'features-section',
  'filters-card',
  'hero-content',
  'hero-content-wrapper',
  'hero-cta-buttons',
  'hero-description',
  'hero-github-button',
  'hero-section',
  'hero-start-building',
  'hero-title',
  'landing-page-root',
  'loading-card',
  'login-divider',
  'login-error',
  'login-footer',
  'login-form',
  'login-header',
  'login-page',
  'logo-section',
  'logs-table-card',
  'main-footer',
  'main-header',
  'main-nav',
  'main-wrapper',
  'mongodb-highlight',
  'nav-actions',
  'nav-dashboard-button',
  'nav-login-button',
  'nav-register-button',
  'next-page-button',
  'page-button-1',
  'page-button-2',
  'page-button-3',
  'page-button-4',
  'page-button-5',
  'page-button-dynamic',
  'pagination-card',
  'permissions-card',
  'permissions-content',
  'permissions-tab',
  'prev-page-button',
  'protected-route-loading',
  'register-divider',
  'register-error',
  'register-footer',
  'register-form',
  'register-header',
  'register-page',
  'role-badge',
  'role-badge-dynamic',
  'role-label',
  'search-button',
  'search-input',
  'search-label',
  'sessions-card',
  'sessions-content',
  'sessions-tab',
  'social-login-buttons',
  'social-register-buttons',
  'start-date-input',
  'start-date-label',
  'stat-card-0',
  'stat-card-1',
  'stat-card-2',
  'stat-card-3',
  'stats-content',
  'stats-grid',
  'stats-section',
  'tabs-list',
  'tech-badge-0',
  'tech-badge-1',
  'tech-badge-2',
  'tech-badge-3',
  'tech-badge-4',
  'tech-badge-5',
  'tech-letter-0',
  'tech-letter-1',
  'tech-letter-2',
  'tech-letter-3',
  'tech-letter-4',
  'tech-letter-5',
  'tech-stack-section',
  'user-details-error',
  'user-details-loading',
  'user-details-page',
  'user-filter-label',
  'user-info-card',
  'user-profile-card',
  'user-section',
  'user-tabs',
  'users-filters',
  'users-page',
  'users-table-card',
  'verified-badge',
  'welcome-message'
] as const;

// Type guard to check if a string is a valid component ID
export function isValidComponentId(id: string): id is ComponentRegistryId {
  return VALID_COMPONENT_IDS.includes(id as any);
}

// Validation function that throws if ID is invalid
export function validateComponentId(id: string): asserts id is ComponentRegistryId {
  if (!isValidComponentId(id)) {
    throw new Error(`Invalid component ID: "${id}". Valid IDs are: ${VALID_COMPONENT_IDS.join(', ')}`);
  }
}

// Generated component definitions placeholder
export const generatedComponentDefinitions = {};
