import { createRegistry, ComponentMeta } from './lib/dev-container';

// Define your component metadata
const components: ComponentMeta[] = [
  {
    id: 'landing-page',
    name: 'Landing Page',
    description: 'Main landing page component with hero section and call-to-action',
    filePath: 'src/pages/Landing.tsx',
    category: 'page',
    semanticTags: ['landing', 'hero', 'homepage', 'main'],
    dependencies: [],
  },
  {
    id: 'app-root',
    name: 'App Root',
    description: 'Root application component that wraps the entire app',
    filePath: 'src/App.tsx',
    category: 'layout',
    semanticTags: ['app', 'root', 'wrapper', 'main'],
    dependencies: [],
  },
  {
    id: 'hero-section',
    name: 'Hero Section',
    description: 'Main hero section with title and call-to-action buttons',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['hero', 'title', 'cta', 'main'],
    dependencies: [],
  },
  {
    id: 'stats-section',
    name: 'Stats Section',
    description: 'Statistics display section with build metrics',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['stats', 'metrics', 'performance'],
    dependencies: [],
  },
  {
    id: 'features-section',
    name: 'Features Section',
    description: 'Feature highlights with icons and descriptions',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['features', 'highlights', 'benefits'],
    dependencies: [],
  },
  {
    id: 'tech-stack-section',
    name: 'Tech Stack Section',
    description: 'Technology stack showcase with logos',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['tech', 'stack', 'technologies'],
    dependencies: [],
  },
  {
    id: 'cta-section',
    name: 'Call to Action Section',
    description: 'Final call-to-action section with project start buttons',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['cta', 'action', 'start', 'project'],
    dependencies: [],
  },
  // Hero section buttons
  {
    id: 'hero-start-building',
    name: 'Start Building Button',
    description: 'Primary call-to-action button for starting to build with the template',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['button', 'cta', 'primary', 'hero'],
    dependencies: [],
  },
  {
    id: 'hero-github-button',
    name: 'View on GitHub Button',
    description: 'Secondary button to view the project on GitHub',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['button', 'secondary', 'github', 'hero'],
    dependencies: [],
  },
  // Stats cards
  {
    id: 'stat-card-0',
    name: 'Build Time Stat Card',
    description: 'Statistical card showing build time metrics',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'stats', 'build', 'performance'],
    dependencies: [],
  },
  {
    id: 'stat-card-1',
    name: 'Bundle Size Stat Card',
    description: 'Statistical card showing bundle size metrics',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'stats', 'bundle', 'size'],
    dependencies: [],
  },
  {
    id: 'stat-card-2',
    name: 'TypeScript Stat Card',
    description: 'Statistical card showing TypeScript coverage',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'stats', 'typescript', 'coverage'],
    dependencies: [],
  },
  {
    id: 'stat-card-3',
    name: 'Performance Stat Card',
    description: 'Statistical card showing performance grade',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'stats', 'performance', 'grade'],
    dependencies: [],
  },
  // Feature cards
  {
    id: 'feature-card-0',
    name: 'Lightning Fast Feature Card',
    description: 'Feature card highlighting lightning fast development',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'feature', 'speed', 'vite'],
    dependencies: [],
  },
  {
    id: 'feature-card-1',
    name: 'MongoDB + Prisma Feature Card',
    description: 'Feature card highlighting database integration',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'feature', 'database', 'mongodb', 'prisma'],
    dependencies: [],
  },
  {
    id: 'feature-card-2',
    name: 'TypeScript Ready Feature Card',
    description: 'Feature card highlighting TypeScript support',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'feature', 'typescript', 'types'],
    dependencies: [],
  },
  {
    id: 'feature-card-3',
    name: 'Deploy Anywhere Feature Card',
    description: 'Feature card highlighting deployment flexibility',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'feature', 'deployment', 'hosting'],
    dependencies: [],
  },
  // Tech badges
  {
    id: 'tech-badge-0',
    name: 'Vite Technology Badge',
    description: 'Technology badge for Vite',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['badge', 'tech', 'vite', 'build'],
    dependencies: [],
  },
  {
    id: 'tech-badge-1',
    name: 'React Technology Badge',
    description: 'Technology badge for React',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['badge', 'tech', 'react', 'framework'],
    dependencies: [],
  },
  {
    id: 'tech-badge-2',
    name: 'TypeScript Technology Badge',
    description: 'Technology badge for TypeScript',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['badge', 'tech', 'typescript', 'types'],
    dependencies: [],
  },
  {
    id: 'tech-badge-3',
    name: 'MongoDB Technology Badge',
    description: 'Technology badge for MongoDB',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['badge', 'tech', 'mongodb', 'database'],
    dependencies: [],
  },
  {
    id: 'tech-badge-4',
    name: 'Prisma Technology Badge',
    description: 'Technology badge for Prisma',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['badge', 'tech', 'prisma', 'orm'],
    dependencies: [],
  },
  {
    id: 'tech-badge-5',
    name: 'Tailwind Technology Badge',
    description: 'Technology badge for Tailwind CSS',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['badge', 'tech', 'tailwind', 'css'],
    dependencies: [],
  },
  // CTA buttons
  {
    id: 'cta-start-project',
    name: 'Start Project Button',
    description: 'Primary CTA button to start a new project',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['button', 'cta', 'primary', 'project'],
    dependencies: [],
  },
  {
    id: 'cta-join-community',
    name: 'Join Community Button',
    description: 'Secondary CTA button to join the community',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['button', 'cta', 'secondary', 'community'],
    dependencies: [],
  },
  // Authentication Components
  {
    id: 'login-page',
    name: 'Login Page',
    description: 'Complete login page with email/password and social authentication',
    filePath: 'src/components/auth/Login.tsx',
    category: 'page',
    semanticTags: ['login', 'auth', 'authentication', 'signin'],
    dependencies: ['better-auth', 'react-router-dom'],
  },
  {
    id: 'login-header',
    name: 'Login Header',
    description: 'Header section of the login page with title and description',
    filePath: 'src/components/auth/Login.tsx',
    category: 'ui',
    semanticTags: ['header', 'login', 'title'],
    dependencies: [],
  },
  {
    id: 'login-error',
    name: 'Login Error Alert',
    description: 'Error message display for login failures',
    filePath: 'src/components/auth/Login.tsx',
    category: 'ui',
    semanticTags: ['alert', 'error', 'login'],
    dependencies: [],
  },
  {
    id: 'social-login-buttons',
    name: 'Social Login Buttons',
    description: 'Google and GitHub social authentication buttons',
    filePath: 'src/components/auth/Login.tsx',
    category: 'ui',
    semanticTags: ['social', 'oauth', 'google', 'github'],
    dependencies: [],
  },
  {
    id: 'login-divider',
    name: 'Login Divider',
    description: 'Visual divider between social and email login',
    filePath: 'src/components/auth/Login.tsx',
    category: 'ui',
    semanticTags: ['divider', 'separator'],
    dependencies: [],
  },
  {
    id: 'login-form',
    name: 'Login Form',
    description: 'Email and password login form',
    filePath: 'src/components/auth/Login.tsx',
    category: 'ui',
    semanticTags: ['form', 'email', 'password', 'login'],
    dependencies: [],
  },
  {
    id: 'login-footer',
    name: 'Login Footer',
    description: 'Footer with link to registration page',
    filePath: 'src/components/auth/Login.tsx',
    category: 'ui',
    semanticTags: ['footer', 'link', 'register'],
    dependencies: [],
  },
  {
    id: 'register-page',
    name: 'Register Page',
    description: 'Complete registration page with form validation',
    filePath: 'src/components/auth/Register.tsx',
    category: 'page',
    semanticTags: ['register', 'signup', 'auth', 'authentication'],
    dependencies: ['better-auth', 'react-router-dom'],
  },
  {
    id: 'register-header',
    name: 'Register Header',
    description: 'Header section of the register page',
    filePath: 'src/components/auth/Register.tsx',
    category: 'ui',
    semanticTags: ['header', 'register', 'title'],
    dependencies: [],
  },
  {
    id: 'register-error',
    name: 'Register Error Alert',
    description: 'Error message display for registration failures',
    filePath: 'src/components/auth/Register.tsx',
    category: 'ui',
    semanticTags: ['alert', 'error', 'register'],
    dependencies: [],
  },
  {
    id: 'social-register-buttons',
    name: 'Social Register Buttons',
    description: 'Google and GitHub social registration buttons',
    filePath: 'src/components/auth/Register.tsx',
    category: 'ui',
    semanticTags: ['social', 'oauth', 'google', 'github'],
    dependencies: [],
  },
  {
    id: 'register-divider',
    name: 'Register Divider',
    description: 'Visual divider between social and email registration',
    filePath: 'src/components/auth/Register.tsx',
    category: 'ui',
    semanticTags: ['divider', 'separator'],
    dependencies: [],
  },
  {
    id: 'register-form',
    name: 'Register Form',
    description: 'Email, password, and name registration form',
    filePath: 'src/components/auth/Register.tsx',
    category: 'ui',
    semanticTags: ['form', 'email', 'password', 'name', 'register'],
    dependencies: [],
  },
  {
    id: 'register-footer',
    name: 'Register Footer',
    description: 'Footer with link to login page',
    filePath: 'src/components/auth/Register.tsx',
    category: 'ui',
    semanticTags: ['footer', 'link', 'login'],
    dependencies: [],
  },
  {
    id: 'dashboard-page',
    name: 'Dashboard Page',
    description: 'Main dashboard page for authenticated users',
    filePath: 'src/components/auth/Dashboard.tsx',
    category: 'page',
    semanticTags: ['dashboard', 'profile', 'user', 'authenticated'],
    dependencies: ['better-auth', 'react-router-dom'],
  },
  {
    id: 'dashboard-loading',
    name: 'Dashboard Loading',
    description: 'Loading spinner for dashboard authentication check',
    filePath: 'src/components/auth/Dashboard.tsx',
    category: 'ui',
    semanticTags: ['loading', 'spinner', 'dashboard'],
    dependencies: [],
  },
  {
    id: 'dashboard-unauthorized',
    name: 'Dashboard Unauthorized',
    description: 'Unauthorized access message for dashboard',
    filePath: 'src/components/auth/Dashboard.tsx',
    category: 'ui',
    semanticTags: ['unauthorized', 'access', 'denied'],
    dependencies: [],
  },
  {
    id: 'dashboard-header',
    name: 'Dashboard Header',
    description: 'Header bar with title and logout button',
    filePath: 'src/components/auth/Dashboard.tsx',
    category: 'ui',
    semanticTags: ['header', 'navigation', 'logout'],
    dependencies: [],
  },
  {
    id: 'dashboard-content',
    name: 'Dashboard Content',
    description: 'Main content area of the dashboard',
    filePath: 'src/components/auth/Dashboard.tsx',
    category: 'ui',
    semanticTags: ['content', 'main', 'dashboard'],
    dependencies: [],
  },
  {
    id: 'user-profile-card',
    name: 'User Profile Card',
    description: 'Profile card showing user information and avatar',
    filePath: 'src/components/auth/Dashboard.tsx',
    category: 'ui',
    semanticTags: ['profile', 'user', 'card', 'avatar'],
    dependencies: [],
  },
  {
    id: 'dashboard-stats',
    name: 'Dashboard Stats',
    description: 'Statistics and activity information for the user',
    filePath: 'src/components/auth/Dashboard.tsx',
    category: 'ui',
    semanticTags: ['stats', 'activity', 'metrics'],
    dependencies: [],
  },
  {
    id: 'protected-route-loading',
    name: 'Protected Route Loading',
    description: 'Loading state for protected route authentication check',
    filePath: 'src/components/auth/ProtectedRoute.tsx',
    category: 'ui',
    semanticTags: ['loading', 'protected', 'auth', 'route'],
    dependencies: [],
  },
  // Navigation buttons
  {
    id: 'nav-login-button',
    name: 'Navigation Login Button',
    description: 'Login button in navigation header',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['button', 'navigation', 'login', 'auth'],
    dependencies: [],
  },
  {
    id: 'nav-register-button',
    name: 'Navigation Register Button',
    description: 'Get started button in navigation header',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['button', 'navigation', 'register', 'auth'],
    dependencies: [],
  },
  {
    id: 'nav-dashboard-button',
    name: 'Navigation Dashboard Button',
    description: 'Dashboard button in navigation header for authenticated users',
    filePath: 'src/pages/Landing.tsx',
    category: 'ui',
    semanticTags: ['button', 'navigation', 'dashboard', 'auth'],
    dependencies: [],
  },
];

// Create the registry
export const componentRegistry = createRegistry(components);

// Debug the registry creation (remove after testing)
// console.log('Registry created:', {
//   totalComponents: components.length,
//   registryKeys: Object.keys(componentRegistry),
//   appRootExists: !!componentRegistry['app-root'],
//   componentRegistry
// });

// Export individual components for convenience
export const COMPONENT_IDS = {
  LANDING_PAGE: 'landing-page' as const,
  APP_ROOT: 'app-root' as const,
  HERO_SECTION: 'hero-section' as const,
  STATS_SECTION: 'stats-section' as const,
  FEATURES_SECTION: 'features-section' as const,
  TECH_STACK_SECTION: 'tech-stack-section' as const,
  CTA_SECTION: 'cta-section' as const,
  // Authentication Components
  LOGIN_PAGE: 'login-page' as const,
  REGISTER_PAGE: 'register-page' as const,
  DASHBOARD_PAGE: 'dashboard-page' as const,
  PROTECTED_ROUTE_LOADING: 'protected-route-loading' as const,
} as const;