import { createRegistry, ComponentMeta } from './lib/dev-container';

// Define your component metadata
const components: ComponentMeta[] = [
  {
    id: 'landing-page',
    name: 'Landing Page',
    description: 'Main landing page component with hero section and call-to-action',
    filePath: 'src/components/Landing.tsx',
    category: 'page',
    semanticTags: ['landing', 'hero', 'homepage', 'main'],
    dependencies: [],
  },
  {
    id: 'app-root',
    name: 'App Root',
    description: 'Root application component that wraps the entire app',
    filePath: 'src/App.tsx',
    category: 'layout',
    semanticTags: ['app', 'root', 'wrapper', 'main'],
    dependencies: [],
  },
  {
    id: 'hero-section',
    name: 'Hero Section',
    description: 'Main hero section with title and call-to-action buttons',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['hero', 'title', 'cta', 'main'],
    dependencies: [],
  },
  {
    id: 'stats-section',
    name: 'Stats Section',
    description: 'Statistics display section with build metrics',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['stats', 'metrics', 'performance'],
    dependencies: [],
  },
  {
    id: 'features-section',
    name: 'Features Section',
    description: 'Feature highlights with icons and descriptions',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['features', 'highlights', 'benefits'],
    dependencies: [],
  },
  {
    id: 'tech-stack-section',
    name: 'Tech Stack Section',
    description: 'Technology stack showcase with logos',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['tech', 'stack', 'technologies'],
    dependencies: [],
  },
  {
    id: 'cta-section',
    name: 'Call to Action Section',
    description: 'Final call-to-action section with project start buttons',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['cta', 'action', 'start', 'project'],
    dependencies: [],
  },
  // Hero section buttons
  {
    id: 'hero-start-building',
    name: 'Start Building Button',
    description: 'Primary call-to-action button for starting to build with the template',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['button', 'cta', 'primary', 'hero'],
    dependencies: [],
  },
  {
    id: 'hero-github-button',
    name: 'View on GitHub Button',
    description: 'Secondary button to view the project on GitHub',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['button', 'secondary', 'github', 'hero'],
    dependencies: [],
  },
  // Stats cards
  {
    id: 'stat-card-0',
    name: 'Build Time Stat Card',
    description: 'Statistical card showing build time metrics',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'stats', 'build', 'performance'],
    dependencies: [],
  },
  {
    id: 'stat-card-1',
    name: 'Bundle Size Stat Card',
    description: 'Statistical card showing bundle size metrics',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'stats', 'bundle', 'size'],
    dependencies: [],
  },
  {
    id: 'stat-card-2',
    name: 'TypeScript Stat Card',
    description: 'Statistical card showing TypeScript coverage',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'stats', 'typescript', 'coverage'],
    dependencies: [],
  },
  {
    id: 'stat-card-3',
    name: 'Performance Stat Card',
    description: 'Statistical card showing performance grade',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'stats', 'performance', 'grade'],
    dependencies: [],
  },
  // Feature cards
  {
    id: 'feature-card-0',
    name: 'Lightning Fast Feature Card',
    description: 'Feature card highlighting lightning fast development',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'feature', 'speed', 'vite'],
    dependencies: [],
  },
  {
    id: 'feature-card-1',
    name: 'MongoDB + Prisma Feature Card',
    description: 'Feature card highlighting database integration',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'feature', 'database', 'mongodb', 'prisma'],
    dependencies: [],
  },
  {
    id: 'feature-card-2',
    name: 'TypeScript Ready Feature Card',
    description: 'Feature card highlighting TypeScript support',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'feature', 'typescript', 'types'],
    dependencies: [],
  },
  {
    id: 'feature-card-3',
    name: 'Deploy Anywhere Feature Card',
    description: 'Feature card highlighting deployment flexibility',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['card', 'feature', 'deployment', 'hosting'],
    dependencies: [],
  },
  // Tech badges
  {
    id: 'tech-badge-0',
    name: 'Vite Technology Badge',
    description: 'Technology badge for Vite',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['badge', 'tech', 'vite', 'build'],
    dependencies: [],
  },
  {
    id: 'tech-badge-1',
    name: 'React Technology Badge',
    description: 'Technology badge for React',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['badge', 'tech', 'react', 'framework'],
    dependencies: [],
  },
  {
    id: 'tech-badge-2',
    name: 'TypeScript Technology Badge',
    description: 'Technology badge for TypeScript',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['badge', 'tech', 'typescript', 'types'],
    dependencies: [],
  },
  {
    id: 'tech-badge-3',
    name: 'MongoDB Technology Badge',
    description: 'Technology badge for MongoDB',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['badge', 'tech', 'mongodb', 'database'],
    dependencies: [],
  },
  {
    id: 'tech-badge-4',
    name: 'Prisma Technology Badge',
    description: 'Technology badge for Prisma',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['badge', 'tech', 'prisma', 'orm'],
    dependencies: [],
  },
  {
    id: 'tech-badge-5',
    name: 'Tailwind Technology Badge',
    description: 'Technology badge for Tailwind CSS',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['badge', 'tech', 'tailwind', 'css'],
    dependencies: [],
  },
  // CTA buttons
  {
    id: 'cta-start-project',
    name: 'Start Project Button',
    description: 'Primary CTA button to start a new project',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['button', 'cta', 'primary', 'project'],
    dependencies: [],
  },
  {
    id: 'cta-join-community',
    name: 'Join Community Button',
    description: 'Secondary CTA button to join the community',
    filePath: 'src/components/Landing.tsx',
    category: 'ui',
    semanticTags: ['button', 'cta', 'secondary', 'community'],
    dependencies: [],
  },
];

// Create the registry
export const componentRegistry = createRegistry(components);

// Export individual components for convenience
export const COMPONENT_IDS = {
  LANDING_PAGE: 'landing-page' as const,
  APP_ROOT: 'app-root' as const,
  HERO_SECTION: 'hero-section' as const,
  STATS_SECTION: 'stats-section' as const,
  FEATURES_SECTION: 'features-section' as const,
  TECH_STACK_SECTION: 'tech-stack-section' as const,
  CTA_SECTION: 'cta-section' as const,
} as const;